### ISSUE TITLE
[Server Change:] Skibidi Toilet Plugin

### ISSUE THREAD

**Issue by PandanNoob** [lincolnsmp/court#1]
### Minecraft Username

the_panba_boss

### Rule Suggestion

Because it is sigma

### Suggestion type

New rule

### Please check the following before submitting

- [X] I have checked the current rules and current open issues for a duplicate suggestion
- [X] I have provided ample reasoning for my suggestion

**Comment by httphypixelnet** [comment]
You see this is the type of issue which will get you blocked from creating submissions like this

**Comment by PandanNoob** [comment]
> You see this is the type of issue which will get you blocked from creating submissions like this

You asked me to make an example
